### ISSUE TITLE
Getting RGB values in addition to Depth Values

### ISSUE THREAD

**Issue by thechargedneutron** [AtsushiSuzuki/unity-depthcapture-ios#2]
I am attempting to obtain RGB values as well apart from the depth values as demonstrated in the project. I added the following lines of code in `CaptureButton.cs`:

I modified the [this](https://github.com/AtsushiSuzuki/unity-depthcapture-ios/blob/d8ab3f7bcf923717d378c9e6d4b0f793e95e2cdf/DepthCapturePlugin/Assets/CaptureButton.cs#L40) line with the following:

> capture_.AcquireNextFrame((pVideoData,` videoWidth, videoHeight, pDepthData, depthWidth, depthHeight) =>
            {
                video_width = videoWidth;
                video_height = videoHeight;
                video_pixels = new float[3 * video_width * video_height];
                Marshal.Copy(pVideoData, video_pixels, 0, 3 * video_width * video_height);
                width = depthWidth;
                height = depthHeight;
                pixels = new float[width * height];
                Marshal.Copy(pDepthData, pixels, 0, width * height);
            });

And then [this](https://github.com/AtsushiSuzuki/unity-depthcapture-ios/blob/d8ab3f7bcf923717d378c9e6d4b0f793e95e2cdf/DepthCapturePlugin/Assets/CaptureButton.cs#L53) with the following:

> var v_depth = pixels[y * width + x];
                    var v_blue = video_pixels[y * width + x];
                    var v_green = video_pixels[width * height + y * width + x];
                    var v_red = video_pixels[2 * width * height + y * width + x];

But this somehow does not work. Also when I try to print the maximum and minimum values in each channel RGBD, only the D value is sensible. RGB has max of around 10e38 and min of similar magnitude.

Any hints on how to achieve RGB channel values also?

**Comment by suzuki-safie** [comment]
color buffer format is 8bit integer per color * 4 channel per pixel (RGBA but alpha is not used).

**Comment by thechargedneutron** [comment]
@AtsushiSuzuki  Thanks for your comment which now is unavailable. I changed the `float` to `byte`. Still it seems the RGB is not visible. Am I doing something incorrect in `Marshal.Copy` part?

**Comment by AtsushiSuzuki** [comment]
sorry, I commented with wrong account.
I'll inspect the code so wait a minute.

**Comment by AtsushiSuzuki** [comment]
Try this.
(for now I don't have mac so I can't create fully working example)

```csharp
                video_width = videoWidth;
                video_height = videoHeight;
                video_pixels = new byte[4 * width * height];
                Marshal.Copy(pVideoData, video_pixels, 0, 4 * videoWidth * videoHeight);
```

```csharp
                    var v_blue = video_pixels[(y * video_width + x) * 4 + 0];
                    var v_green = video_pixels[(y * video_width + x) * 4 + 1];
                    var v_red = video_pixels[(y * video_width + x) * 4 + 2];
```

- depth size (width*height) may differ from video size, so if you want RGBD, you may need to rescale
- depth format is float, pixel format is 8bit integer (* 3 channels)

**Comment by thechargedneutron** [comment]
Thanks a lot!! This works. :)
